---
dependencies:
  - role: common
    when: ansible_distribution == 'Ubuntu'
  - role: supervisor
    when:
      - NEWRELIC_LOGWATCH
      - ansible_distribution == 'Ubuntu'
  - role: rbenv
    common_web_user: "root"
    rbenv_user: "root"
    rbenv_dir: "{{ rbenv_root_dir }}"
    rbenv_ruby_version: "1.9.3-p547"
    when:
      - NEWRELIC_LOGWATCH
      - ansible_distribution == 'Ubuntu'
